CREATE TABLE membership (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE  NULL
);

CREATE TABLE gym_class (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    schedule TIMESTAMP NOT NULL
);

CREATE TABLE workout (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    program_id BIGINT NOT NULL,
    details TEXT,
	workout_date date not null
);

CREATE TABLE equipment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL
);

CREATE TABLE users (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(50),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    PASSWORD VARCHAR(255),
    LAST_LOGIN TIMESTAMP
);

CREATE TABLE GYM_PROGRAMS (
    PROGRAM_ID bigint PRIMARY KEY AUTO_INCREMENT,
    PROGRAM_NAMES VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    CHARGES DECIMAL(10, 2),
    PERIOD VARCHAR(50)
);
